name: "Run Trivy Scan"

on:
  push:
    branches:
      - main

env:
  VERSION: $(( $(cat version.txt) + 1 ))

jobs:
  
  run_container_image_scan_on_supermario_docker_image:
    runs-on: ubuntu-latest
  
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKERHUB_TOKEN }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Get Docker Image from Docker Hub
        run: |
          echo "Pulling Docker image version: ${{ env.VERSION }}"
          docker pull armaan491/argocd:${{ env.VERSION }}
          docker tag armaan491/argocd:${{ env.VERSION }} supermariolatestdockerimage:${{ env.VERSION }}
          docker save -o /github/workspace/supermariolatestdockerimage.tar supermariolatestdockerimage:${{ env.VERSION }}
      
      - name: Run Trivy vulnerability scanner on the tarball
        uses: aquasecurity/trivy-action@v0.6.0
        with:
          input: /github/workspace/supermariolatestdockerimage.tar
          exit-code: '1'
          severity: 'CRITICAL,HIGH'

      - name: Upload the scan report as an artifact (optional)
        uses: actions/upload-artifact@v3
        with:
          name: trivy-report
          path: /github/workspace/supermariolatestdockerimage.tar
